[package]
name = "vcf2parquet-bin"
version = "0.1.0"


[dependencies]
vcf2parquet-lib = { path = "../vcf2parquet-lib", version = "0.1.0" }

# logging management
simplelog = { version = "0.11" }

# cli management
clap      = { version = "3", features = ["derive"] }