[package]
name = "vcf2parquet-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
# input output management
niffler     = { version = "2" }
noodles     = { version = "0.18", features = ["vcf"] }
arrow       = { version = "9" }

# logging and error management
log         = { version = "0.4" }
thiserror   = { version = "1" }